# Generated by Django 3.2.25 on 2024-08-09 08:58

from django.db import migrations, models


def copy_note_to_customer_note(apps, schema_editor):
    Checkout = apps.get_model("checkout", "Checkout")
    Checkout.objects.filter(note__isnull=False).update(customer_note=models.F("note"))


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0069_merge_20240514_1008"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="customer_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(copy_note_to_customer_note),
    ]
